- frontend/src/pages/Cart/Cart.css
While a minor change for User experience almost similar colour text on a background is not suitable and is better to be aligned with contrast to highlight important details to grab users attention 
Here mainly changes 
-color of cart item listing for user to be able to reconfirm their cart
-Be able to more prominantly see Cart total heading and price
- Heading of Promo Code tag made more visible to encourage people to use discounts which will overall help convey more orders in a buisness
- A lot more UI design changes can be made which i will look further into as i go through the code base
(after my exams)
Hope My changes are accepted and still well in the Code
-As this was my first ever PR looking forward to contributing more
> updated colour of 3 almost unreadable text element

- frontend/src/components/Footer/Footer.css
- frontend/src/components/Footer/Footer.js
#10 
styled the footer with a modern look.
> #10 styled footer

- backend/controllers/userController.js
- backend/models/userModel.js
- backend/routes/userRoute.js
- frontend/src/components/LoginPopup/LoginPopup.js
This PR introduces an email service integration for the forgot password and reset password functionality. Below are the key updates:
Features:
Password Reset Functionality:
In the userController.js file, integrated the logic for handling forgotten passwords. When a user requests a password reset, a token is generated and stored in the database with an expiration time of 1 hour.
A reset URL is dynamically generated and sent to the user's email address using Nodemailer.
By default, Gmail's SMTP service is used for sending the password reset email. However, developers can easily replace this with other email services such as SendGrid, Mailgun, or AWS SES depending on project requirements. The email configuration can be updated in the environment variables (e.g., EMAIL_SERVICE, …
> Implemented password reset feature with email service integration

- frontend/src/App.js
- frontend/src/components/Navbar/Navbar.js
- frontend/src/pages/Subscription/Subscription.css
- frontend/src/pages/Subscription/Subscription.js
Hi @Mahak008 ,
I added The Subscription Page, which looks like this
changes are made at SubscriptionPage branch. Merge the branch based on your need .
Happy Coding,
Abhiraj Sardar
> Added Subscription Page

- frontend/src/App.js
- frontend/src/components/Footer/Footer.css
- frontend/src/components/Footer/Footer.js
- frontend/src/components/Navbar/Navbar.css
- frontend/src/components/Navbar/Navbar.js
- frontend/src/pages/ContactUs/ContactUs.css
- frontend/src/pages/ContactUs/ContactUs.js
added contact.js & css ; compact look to footer; navbar enhancement and glitch fix
> Added ContactUs page, compact footer look, fixed navbar bug & enhanced css

- admin/index.html
- frontend/src/assets/assets.js
- frontend/src/components/ExploreMenu/ExploreMenu.css
- frontend/src/components/ExploreMenu/ExploreMenu.js
- frontend/src/components/FoodItem/FoodItem.css
- frontend/src/components/Footer/Footer.css
- frontend/src/components/Header/Header.css
- frontend/src/components/Header/Header.js
- frontend/src/components/LoginPopup/LoginPopup.css
- frontend/src/components/Navbar/Navbar.css
- frontend/src/components/Navbar/Navbar.js
- frontend/src/index.css
- frontend/src/pages/Cart/Cart.css
- frontend/src/pages/Cart/Cart.js
- frontend/src/pages/PlaceOrder/PlaceOrder.css
Hey @Mahak008 !
I am delighted to have gained this opportunity to work with you and contribute to your amazing project. I am equally excited to see if you will like it. I have put my best efforts via contributing to #3 .
The changes made to enhance UI are as follows:
1. Fixed the navbar                                    
2. Touch-ups on 'Header' card via adding shadow to it and updates on its text
3. Sign-up form pop up updated
4. Cart enhanced
5. Menu enhanced
6. Enhancing Footer
7. Summing up, changed overall UI of project
Looking forward to a positive response. 
Thank you.
> Modified frontend to enhance UI #3 (under SWOC)

- frontend/src/components/FoodItem/FoodItem.css
> #48: Prevent stretching rating stars

- backend/controllers/cartController.js
- backend/controllers/foodController.js
- backend/models/foodModel.js
- backend/models/userModel.js
Fixes #19 
- Added `day` and `timeSlot` fields to the **foodSchema** to define meal availability based on specific days and time slots (e.g., Thursday Lunch).  
---
- Introduced a `subscription` field (default: `false`) to track whether a user is a subscriber.  
---
- Modified the `addFood` controller to accept and store `day` and `timeSlot` values for meals during food addition.  
---
- Implemented validation in the `addToCart` controller to restrict non-subscribers from adding meals that are not available for the **current day and time slot**.  
- Subscribers can continue adding any meal without restrictions.  
---
- Added meaningful error messages for non-subscribers attempting to order meals outside allowed time slots.
> Restriction for non subscribers

- .github/PULL_REQUEST_TEMPLATE.md
- backend/controllers/foodController.js
- backend/models/foodModel.js
- backend/routes/foodRoute.js
Fixes #9 
- Added a **reviews array** in the food schema to store user reviews (rating and comment).
- Added an **averageRating** field to store the dynamic average rating for each food item.
- **Validation:** Ensures input data (rating, foodId, userId) is valid.
- **Duplicate Handling:** Checks if the user has already reviewed the item and updates the existing review if found.
- **Average Rating Calculation:** Recalculates the average rating based on all reviews whenever a new review is added or updated.
- Added a **POST /addReview** route for submitting and updating reviews.
- Provides meaningful error messages for invalid input, missing data, or food items not found.
> Add Review Feature with Dynamic Rating Calculation

- frontend/public/index.html
- frontend/src/index.css
- frontend/src/index.js
To improve the user experience on the homepage, a fixed scroll button was implemented. This button provides quick and seamless navigation, allowing users to return to the top of the page or any predefined section with a single click. Here’s a detailed breakdown of the feature:
---
- **Positioning**: The scroll button is fixed to the bottom-right corner of the screen, ensuring it remains visible as the user scrolls down the page.  
- **Appearance**: The button is styled with CSS to include a minimalist design, often represented as an upward arrow or similar icon. Hover effects are added for better interactivity.  
- **Responsiveness**: The button scales appropriately for different screen sizes and resolutions, ensuring usability across desktops, tablets, and mobile devices.  
---
- The …
> Updating the scroll button to the homepage

- backend/dockerfile
The repository currently lacks a Dockerfile, which is essential for creating a containerized environment for the application. A Dockerfile will allow developers and contributors to easily set up the application in a consistent environment, regardless of the system configuration. This will help ensure that the application runs smoothly across different environments and simplifies the process of deploying to various platforms.
Closes #41
> Dockerfile Creation for Project

- .github/PULL_REQUEST_TEMPLATE.md
> Added template for pull request

- frontend/src/App.js
- frontend/src/components/HappyClients/HappyClients.css
- frontend/src/components/HappyClients/HappyClients.js
- frontend/src/components/Navbar/Navbar.css
This pr fixes issue #83 
This pull request addresses the issue of adding a "Happy Clients" section at the bottom of the page to showcase customer testimonials. The section is designed to match the existing dark theme with orange accents and includes animations for a modern look.
- Added HappyClients component to display customer testimonials.
- Included animations for the testimonials to appear smoothly when scrolled into view.
- Created HappyClients.css to style the new section, ensuring it matches the dark theme with orange accents.
- Updated the color scheme to use the same orange as the rest of the website.
- Integrated the HappyClients component into the main App.js file, placing it before the footer.
> [FEATURE] Added a happy clients section a the bottom of the page.

- backend/.gitignore
- backend/controllers/cartController.js
- backend/controllers/orderController.js
- backend/node_modules/.package-lock.json
- backend/package-lock.json
- backend/package.json
- frontend/public/index.html
- frontend/src/pages/PlaceOrder/PlaceOrder.js
- frontend/src/pages/Verify/Verify.js
This PR resolve Issue #4 and closes it.
Removed existing stripe payment gateway and implemented full fledged razorpay gateway.
backend env file additions required:
```
RAZORPAY_KEY_ID=
RAZORPAY_SECRET_KEY=
```
Demo Video of a payment in test mode:
https://github.com/user-attachments/assets/907e9e1c-78cf-474c-ab24-817e2f4a2142
> feat: Implement Razorpay Payment Gateway by removing Stripe

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/FeedbackForm/Feedback.css
- frontend/src/components/FeedbackForm/Feedback.js
(https://github.com/Mahak008/HungryBox/issues/88#issue-2777379139)
created a fresh look for the feedback form, fully immune to light/dark mode changes
framer motion was installed during the process of improving the feedback form
> feedback-section-fixed

- frontend/src/components/Navbar/Navbar.css
- frontend/src/pages/Cart/Cart.css
(https://github.com/Mahak008/HungryBox/issues/90)
Fixed cart spacing issue, and light mode immunity for cart and navbar
> Fixed cart spacing issue, and light mode immunity for cart and navbar

- frontend/src/App.js
- frontend/src/pages/Subscription/Subscription.css
- frontend/src/pages/Subscription/Subscription.js
https://github.com/Mahak008/HungryBox/issues/89#issue-2777387052
subscriptions page enhanced and theme bug fixed in App.js
> subscriptions-page-enhanced/theme-bug-fixed

- frontend/package-lock.json
- frontend/public/index.html
- frontend/src/components/Footer/Footer.css
- frontend/src/components/Footer/Footer.js
The issue is with the footer styles there are some issues with the UI i have fixed it.
i Have fixed the issue of UI of footer and make it perfectly responsive for all devices.
> Fixed Footer with responsive design

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Navbar/ThemeToggle.js
Related Issue
This pull request resolves #45 
Changes Made
Replaced the text for "Light Mode" and "Dark Mode" with icons (sun and moon) to enhance the user interface for toggling between light and dark themes.
Integrated the react-icons library to add the FaSun and FaMoon icons, which dynamically update based on the current theme.
Updated the ThemeToggle component to conditionally render the icons instead of text based on the selected theme.
Type of Change
[ ] New Feature
[ ] Improvement
> Improvised icons for theme toggle button

- frontend/src/components/LoginPopup/LoginPopup.js
Closes : #31 
Sign Up page name field validation added.
> 🛠️ Fix : Sign Up page name field validation added

- admin/src/App.jsx
- admin/src/components/Loading/Loading.jsx
Close #113 
- Added `isDarkMode` to `Orders` component
- fixed svg in React errors like spelling errors of attribute strokeWidth and className
Not Applicable
I am making this PR under SWOC program as a student contributor.
> [🐞Bug Fix]: Fixed console errors and Order component missing props error

- backend/src/config/db.ts
- backend/src/server.ts
Close #111 
- improved dotenv config loading with specified path
- moved mongo_uri initialisation from function context to inside the function, reducing the chances of getting it undefined.
Not Applicable
I am a beginner contributor making this PR under SWOC programme.
> [❗Error]: Proper dotenv config call and mongo_uri initialization

- frontend/src/App.js
- frontend/src/components/Navbar/Navbar.css
- frontend/src/components/Navbar/Navbar.js
- frontend/src/components/Navbar/ThemeToggle.js
This PR resolves the issue #107 
Closes #107 
- Placed the theme switcher button inside the navbar component
- Improved the responsiveness of the navbar in tablet and mobile mode.
- Also add some extra CSS
> Fixed some responsiveness of the navbar 

- frontend/src/components/ExploreMenu/ExploreMenu.css
Issue Number #119 
I have changed the default color to a new color that will work on both of the dark and light theme perfectly.
> Fixed Color

- frontend/src/index.css
#132
Enhanced the UI of the scroll bar
> Added UI for scroll bar

- .github/ISSUE_TEMPLATE/backend_issue.yml
- .github/ISSUE_TEMPLATE/bugreport.yml
- .github/ISSUE_TEMPLATE/documentation_update.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/frontend_issue.yml
- .github/PULL_REQUEST_TEMPLATE.md
> Done adding all issue templates and pull request templates !!

- README.md
- frontend/src/pages/PlaceOrder/PlaceOrder.css
- frontend/src/pages/PlaceOrder/PlaceOrder.js
This PR adds the feature on the cart page, if the user enters city other than New Delhi, then a message must pop up , our services do not cater outside delhi.
Fixes #135 
Closes #135 
https://github.com/user-attachments/assets/93eec7b9-010d-49d0-9f94-b88e003356f3
> fix: added city validation in cart

- frontend/src/components/ExploreMenu/ExploreMenu.css
- frontend/src/components/KitchenToDoorstep/KitchenToDoorstep.css
- frontend/src/index.css
This PR adjusts the layout on mobile devices to ensure that content boxes take up the full width of the screen. Previously, the boxes had unnecessary margins, making the layout feel constrained. Now, they expand properly while maintaining adequate padding for readability.
- Updated CSS to make content boxes responsive.
- Ensured proper padding and spacing for a balanced design.
> #145: Ensure Full-Width Boxes on Mobile

- frontend/src/components/FeedbackForm/Feedback.css
button ui fix of feedback button . 
Closes #150
> UI fix of button

- frontend/src/components/Footer/Footer.css
- frontend/src/components/Footer/Footer.jsx
in this pr i have added 3d hover effect and animation to social media icons and also added underline animation effect to all nav items .  to make the website more engaging.
Closes #148 
https://github.com/user-attachments/assets/c9f496fe-b9a9-4121-a258-7a1efe12f620
> UI fixed of footer
